services:
  database:
    image: postgres:15-alpine
    restart: always
    container_name: database
    networks:
      - red
    environment:
      - POSTGRES_DB=dbcart
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbcart
    volumes:
      - data:/var/lib/
    ports:
      - 5000:5432

  backend:
    build:
      dockerfile: ./Dockerfile
    restart: always
    container_name: backend
    depends_on:
      - database
    networks:
      - red
    ports:
      - 9000:8080

networks:
  red:

volumes:
  data:
